apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service-ui
  template:
    metadata:
      labels:
        app: team-service-ui
    spec:
      containers:
      - name: team-service-ui
        image: vishkumar/team-service-ui:1.0.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-k8t-secret
---
apiVersion: v1
kind: Service
metadata:
  name: team-service-ui-service
spec:
  selector:
    app: team-service-ui
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 80   # Port on the container
      nodePort: 30010  # Or any available port between 30000 and 32767
  type: NodePort

